site_name: Birdie Docs
nav:
    - Home: index.md
    - Agency Hub:
        - agency-hub.md
        - Assessments:
            - 'agency-hub/assessments/assessments.md'
            - 'Details': 'agency-hub/assessments/details.md'
            - 'FAQs': 'agency-hub/assessments/faqs.md'
        - 'Alerts': 'agency-hub/alerts.md'
        - 'Medication Scheduling': 'agency-hub/med-scheduling.md'
        - 'Task Manager': 'agency-hub/tasks.md'
        - 'Visit Planning': 'agency-hub/visit-planning.md'


    - Care Professional App: care-pro-app.md
    - Family App: family-app.md
    - Third Party Access: third-party-access.md
    - Services: services.md
theme: 
    name: material
    language: en
    palette:
        scheme: preference
        primary: deep purple
        accent: pink
    icon:
        # logo: 'images/birdie_logo_white'
        favicon: 'images/favicon.ico'
# extra:
#     social:
#         - icon: fontawesome/brands/window-maximise
#         link: https://www.birdie.care/
#         - icon: fontawesome/brands/twitter
#         link: https://twitter.com/BirdieCare
#         - icon: fontawesome/brands/linkedin
#         link: https://www.linkedin.com/company/birdiecare/